# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8a517aa475648c6d6dc0404b763ff7f7f7e2ab3fbeba93845e68efd179c1bd76b8e0995e8419976f66927a8cf5912a3086d2a171727f422f192e8b99f71e7e9

test:
  secret_key_base: 8701c22a541218d824727071130c51e841d34b3d7de4961734f2458dc68d8610900707f3bb2b27b7483b5f7444540fed310d58cb0540a8a7003085e475a1469b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
